### ISSUE TITLE
ui: show tooltip on action bar item

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-dev/firecamp#103]
**Description**
when the user hovers on the action bar item icon (Explorer, Environments, History) the tooltip needs to be shown.

here we need to do two thing
1. create a tooltip component/api in @firecamp/ui package using mantine
2. use this component/api in the action bar component to show the tooltip

<img width="207" alt="image" src="https://github.com/firecamp-dev/firecamp/assets/5078921/7d9b894e-652a-488c-b873-d0cdb63e732b">

**Comment by madara-uchihaaa** [comment]
May you please elabroate or provide info about this mantine thing ?

**Comment by Dhoni77** [comment]
Hi @Nishchit14  can you assign me this issue.

**Comment by astriskit** [comment]
> May you please elabroate or provide info about this mantine thing ?

I think that could mean the mantine-ui - https://mantine.dev/.

**Comment by ashfaqhaq** [comment]
I would like to work on this as well, please assign it to me incase it hasn't been assigned yet

**Comment by Nishchit14** [comment]
thank you for the PR @Dhoni77 

thank you for showing your interest in this issue @madara-uchihaaa @ashfaqhaq @astriskit. new issues will be coming up soon, keep watching this repo. also, you can review #104 for learning and improvement purposes.

we highly appreciate all kinds of contributions!!
