### ISSUE TITLE
Bad contrast in homepage in dark mode

### ISSUE THREAD

**Issue by Mosaab-Emam** [firecamp-dev/firecamp#112]
**Description**
Just wanted to point out that the heading in the home page doesn't have good contrast in dark mode.

![Screenshot from 2023-10-14 17-15-09](https://github.com/firecamp-dev/firecamp/assets/26435307/1d7a8bf7-0699-400f-8a0b-c5b56ebb716f)

**Comment by debajoti** [comment]
I would love to work on this !

**Comment by Nishchit14** [comment]
@Mosaab-Emam thank you for reporting it. @debajoti the website is not OSS at this moment, but we're seriously thinking of making it OSS. I'll confirm in a day.

**Comment by Nishchit14** [comment]
@debajoti you can work on it, here is the repo https://github.com/firecamp-dev/website

**Comment by Nishchit14** [comment]
@jatingodnani would you like to try this one?

**Comment by Nishchit14** [comment]
Sure @Rockleemode

**Comment by Rockleemode** [comment]
@Nishchit14 

![Screenshot (4)](https://github.com/firecamp-dev/firec
![Screenshot (5)](https://github.com/firecamp-dev/firecamp/assets/96262404/dd579f8c-49f0-42ef-b618-c6758b2badb8)
amp/assets/96262404/9257c8b7-bddc-4181-a7a5-1d2c91d888fc)

look at the before and after i have adjusted the contrast, is it okay should adjust it a little more

**Comment by Rockleemode** [comment]
@Nishchit14 
![Screenshot (7)](https://github.com/firecamp-dev/firecamp/assets/96262404/d33cf4f2-0fea-4c9d-85de-143462905368)
tell me what you think, is it okay or should adjust the contrast more?

![Screenshot (6)](https://github.com/firecamp-dev/firecamp/assets/96262404/38c75f66-91d8-4ea3-b221-4f75c1dd52ae)

**Comment by Mosaab-Emam** [comment]
Try using the brand gradient on the title in dark mode. I think it'll be sick.

**Comment by Nishchit14** [comment]
@Rockleemode It looks better than the previous one, can you please share the PR so we can continue over there? Thanks for your suggestion @Mosaab-Emam

**Comment by Mosaab-Emam** [comment]
Here's my attempt on this...

![Screenshot from 2023-10-21 11-24-48](https://github.com/firecamp-dev/firecamp/assets/26435307/2edfcb63-0a0a-4c84-9b4a-75138576641d)

I'll re-open this issue in [the website repo](https://github.com/firecamp-dev/website) for better tracking. I'll also link my pull request there. I suggest that this issue gets closed.

@Rockleemode @Nishchit14 @debajoti

**Comment by Nishchit14** [comment]
Thank you @Mosaab-Emam and @Rockleemode for your PRs. We'll internally review it and accept one based on our design standards. However, I appreciate all your efforts towards betterment.
