### ISSUE TITLE
feature: Implement request transformation between HAR and Firecamp formats

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-dev/firecamp#115]
### Description: 

Firecamp currently does not have the ability to transform HTTP request/response data between the HAR (HTTP Archive) format and Firecamp's internal request format. 

This feature request is to implement bidirectional conversion:

- [ ] HAR to Firecamp request: Parse a HAR request object and convert it to a Firecamp request object
- [ ] Firecamp request to HAR: Take a Firecamp request object and convert it to a HAR request object

This will allow:

- Importing HAR files from other tools (like browser developer tools) into Firecamp for editing/replay
- Exporting requests edited in Firecamp out to HAR format for use in other tools
- Prepare a code snippet for the request

The implementation should include:

- Mapping of all relevant fields between the two formats
- Helper functions for HAR -> Firecamp and Firecamp -> HAR conversions
- Unit tests validating bidirectional conversion

This feature will enable better interoperability with external tools for importing and exporting HTTP request data.

### Resources
1. Firecamp Request Type: https://github.com/firecamp-dev/firecamp/blob/main/packages/firecamp-types/src/requests/rest/request.ts#L17C25-L17C25
2. https://www.npmjs.com/package/@types/har-format

**Comment by RISHIKESHk07** [comment]
Hey @Nishchit14  would like to contribute , though I have not much knowledge about the above issue.

**Comment by Nishchit14** [comment]
The business logic of this feature is around HAR and Firecamp API Request transformation. Firecamp Rest Request and HAR both have JSON format. We need to create two transformer functions

1. HAR Request to Firecamp Rest Request
2. Firecamp Rest Request to HAR Request

Getting started steps would be
1. create a new package under the `packages/*`, folder name `firecamp-har` and package name in package.json with `@firecamp/firecamp-har`, you can copy the existing package to start with typescript boilerplate
2. start building transformer business logic
3. write jest tests
4. submit PR.

for any kind of help feel free to ask on [Discord's contribution channel.](https://discord.com/invite/8hRaqhK)

### Reference 
**HAR**
JSON: https://gist.github.com/igrigorik/3495174
https://github.com/javieraviles/Har2Postman/blob/master/test/0.1.0/input.json
TS: https://www.npmjs.com/package/@types/har-format

**Firecamp**
JOSN: https://github.com/firecamp-dev/firecamp/blob/d43e50d017d381cfb05ac5408a90d23c935fafc5/packages/firecamp-cli/test/data/restEchoServer.firecamp_collection.json#L124-L190
TS: https://github.com/firecamp-dev/firecamp/blob/main/packages/firecamp-types/src/requests/rest/request.ts#L17C25-L17C25

> @note: only transform request to request, do not consider whole collection transformation as of now.


cc: @RISHIKESHk07

**Comment by jatingodnani** [comment]
@Nishchit14 are you asking to make a toll to convert a har to fire format and vice verse?

**Comment by Nishchit14** [comment]
@jatingodnani yes, format conversion from HAR to Firecamp and Firecamp to HAR.

**Comment by jatingodnani** [comment]
@Nishchit14 where to implement this

**Comment by Nishchit14** [comment]
@jatingodnani please read this https://github.com/firecamp-dev/firecamp/issues/115#issuecomment-1767796283, specific this section `Getting started steps would be`

**Comment by jatingodnani** [comment]
![Screenshot 2023-10-19 121918](https://github.com/firecamp-dev/firecamp/assets/97869761/cf486b88-1c67-4f1f-b1b0-be16efc2b7e0)
@Nishchit14 can you pls tell me is this correct?or i am missing something

**Comment by jatingodnani** [comment]
@Nishchit14 check this above

**Comment by Nishchit14** [comment]
refer this https://github.com/firecamp-dev/firecamp/pull/120#issuecomment-1770504239

I appreciate your efforts to understand this issue.  I need some time to prepare a minimum package so you can start. also the HAR <=> Firecamp comparison looks good at first sight but I prefer to have json in PR so I can review it properly.

**Comment by Nishchit14** [comment]
@jatingodnani yes, it looks correct.

**Comment by jatingodnani** [comment]
@Nishchit14  i am ready to take this issue.

**Comment by jatingodnani** [comment]
@Nishchit14 you have completed this?
