### ISSUE TITLE
[bug]: Unable to type a URL in Safari

### ISSUE THREAD

**Issue by custompro12** [firecamp-dev/firecamp#117]
**Describe the bug**
In Safari, users may be unable to type in the request URL input box.

**To Reproduce**
1. Open Safari
2. Navigate to firecamp.dev
3. Click "Create Rest API"
4. Click the "http://" placeholder to attempt to focus the request URL box
5. Attempt to type but nothing appears

**Expected behavior**
Request URL input should work for Safari users.

**Desktop (please complete the following information):**
 - OS: Ventura 13.6
 - Browser Safari
 - Version 16.6

**Additional context**
I can work around the issue by pressing `TAB` after clicking the "http://" placeholder.  After that, I am able to type in the box.

**Comment by Nishchit14** [comment]
Thank you for reporting this issue, It's fixed. the new release is on the way. you can test it on staging app https://staging.firecamp.dev

**Comment by custompro12** [comment]
> Thank you for reporting this issue, It's fixed. the new release is on the way. you can test it on staging app https://staging.firecamp.dev

It does seem to work for me there.  Thanks!
