### ISSUE TITLE
bug: bearer auth seems to have an issue with auth header creation

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-dev/firecamp#134]
**Describe the bug**
The bearer auth is broken, It is not sending the `Authorization` header to the server.

**Expected behavior**
It should generate the `Authorization` header and send it to the server.

**Comment by lukehollenback** [comment]
Also seeing this.

**Comment by Nishchit14** [comment]
@lukehollenback you can use the header directly as of now, new release will be coming with this fix soon.

**Comment by arunreddy** [comment]
@Nishchit14  - Any updates? Is there a tentative date for the next release?

**Comment by Nishchit14** [comment]
@arunreddy You can expect it within the Dec 2023. I am planning to give a new release in a week. also with new desktop app.

**Comment by arunreddy** [comment]
@Nishchit14  - Great, looking forward to it.

**Comment by Nishchit14** [comment]
@arunreddy the minor version v3.2.4 has been released. feel free to reopen it incase you face any issue.
