### ISSUE TITLE
[bug]: Unable to make http request

### ISSUE THREAD

**Issue by PhillipMwaniki** [firecamp-dev/firecamp#140]
**Describe the bug**
I'm unable to make a http request to an endpoint. I've tried changing the Browser Agent to Cloud Agent but nothing changed.

**To Reproduce**
1. Make a post request to a local domain i.e. myproject.test

**Expected behavior**
A json response from the server, whether successful or not

**Screenshots**
![Screenshot 2023-11-01 at 14 28 56](https://github.com/firecamp-dev/firecamp/assets/2037708/890a13e1-230b-4b2e-82da-a2ab4585acc7)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 118.0.2 (64-bit)

**Comment by Nishchit14** [comment]
Is it a localhost server? @PhillipMwaniki

**Comment by PhillipMwaniki** [comment]
Yeah it's on localhost. I'm using a tool called Herd which creates local domains for my projects

**Comment by Nishchit14** [comment]
The local server can not be accessed by the cloud agent. You can allow `https://firecamp.dev` to allow it locally and set browser agent

Here are other solutions
1. read this CORS note from this doc https://firecamp.io/docs/platform/firecamp-agent#agent-comparison
2. use desktop application, it's coming soon. you can watch this branch https://github.com/firecamp-dev/firecamp/tree/feat/62-desktop

**Comment by PhillipMwaniki** [comment]
Thanks for the prompt response @Nishchit14. I'll watch the branch
