### ISSUE TITLE
[bug]: 404 page when clicking on documentation in navbar

### ISSUE THREAD

**Issue by janvi01** [firecamp-dev/firecamp#158]
**Describe the bug**
https://firecamp.io/docs is accessible but when clicking on `documentation` in the navbar, it displays "404 This page could not be found."

**Expected behavior**
"/docs" should be accessible when clicking on `documentation` in the navbar.

**Screenshots**

<img width="1768" alt="Screenshot 2023-12-16 at 8 09 37 PM" src="https://github.com/firecamp-dev/firecamp/assets/34344234/804ada16-1e35-4ad9-b7b5-4d394983c40c">

**Comment by janvi01** [comment]
Also, The Github Star button beside Pricing doesn't load properly.

**Comment by janvi01** [comment]
I would like to work on this.

**Comment by shreya-gr** [comment]
hey @janvi01 thanks for putting this issue here. 

for doc you need to set "Hard link" instead of "Soft link"

Please go ahead and pick the issue.

**Comment by Nishchit14** [comment]
@janvi01 here is the website repo: https://github.com/firecamp-dev/website

**Comment by janvi01** [comment]
I am not able to reproduce the issue now @Nishchit14
