### ISSUE TITLE
[bug]: unable to open websocket connection

### ISSUE THREAD

**Issue by pranavwani** [firecamp-dev/firecamp#168]
**Describe the bug**
trying to connect to the websocket server, but on click of connect receiving erron in dev tool

**To Reproduce**
1. Go to new request of websocket
2. enter any URL (ex.: wss://echo.websocket.org)
3. click on connect

**Expected behavior**

**Screenshots**
<img width="550" alt="Screenshot 2024-01-13 at 6 08 47 PM" src="https://github.com/firecamp-dev/firecamp/assets/26399261/c29ffdac-bf48-4ade-939f-548687357d1b">

**Desktop (please complete the following information):**
 - OS: mac os

**Additional context**
Working properly in web app (firecamp.dev)

**Comment by Nishchit14** [comment]
It's confirmed that the issue is with desktop app only, the [web app](https://firecamp.dev) is working fine.

<img width="1454" alt="image" src="https://github.com/firecamp-dev/firecamp/assets/5078921/2a561bf7-f5c3-4cd2-b4b3-29dd37b597e6">

**Comment by Nishchit14** [comment]
Shipped with [v3.3.0-beta.3](https://github.com/firecamp-dev/firecamp/releases/tag/v3.3.0-beta.3)
