### ISSUE TITLE
[bug]: [need clarification] Lost GraphQL type tag, unable to switch/view MyMutation

### ISSUE THREAD

**Issue by wangzhou-ccc** [firecamp-dev/firecamp#237]
**Describe the bug**
After clicking the **create graphql playground** button, I enter the API URL normally to get the graphql schema. 
Under Explorer, only query is visible, but I can't switch or view **mutation**. Seems to be lost.
No matter how I refresh/click, you will not be able to display My mutation.
But in the Documentation Explorer, I can see that the mutation is normal, meaning that the IntrospectionQuery API responds normally.
Hopefully the relevant authors can answer whether it is a setup problem or a valid bug. Thank you very much! 
This software is very powerful and does a great job!

**To Reproduce**
As described, as screenshot.

**Expected behavior**
can switch or view **mutation**

**Screenshots**
![image](https://github.com/firecamp-dev/firecamp/assets/68171773/69618fce-a9d6-41b5-bbd9-029dc6d7bbb6)
![image](https://github.com/firecamp-dev/firecamp/assets/68171773/721b6cc5-8b2e-4300-8b11-897843d0693f)

**Desktop (please complete the following information):**
 - OS: WIN 11
 - Browser: Desktop software (the same goes for Google Chrome)
![image](https://github.com/firecamp-dev/firecamp/assets/68171773/46130f11-f954-4d96-a8cd-e1b639483628)

 - Version v3.2.4
![image](https://github.com/firecamp-dev/firecamp/assets/68171773/959dee73-f243-41d5-8718-586bf3d6731e)

**Additional context**

**Comment by Nishchit14** [comment]
@wangzhou-ccc you need to keep at least one mutation query (even empty mutation) in the playground.

**Comment by wangzhou-ccc** [comment]
@Nishchit14 Well, after trying, it's been solved. Thank you for your answers!
