### ISSUE TITLE
Download link is not working. (Mac Intel)

### ISSUE THREAD

**Issue by siniradam** [firecamp-dev/firecamp#240]
**Description**
Download links in Github and [Firecamp](https://firecamp.io/download) website are linked to this URL https://fcamp.co/mac for Intel/Mac build and it returns error.

```
Error: An internal error occurred with Vercel.

Your connection is working correctly.

Vercel is NOT working correctly.

This is an error with the platform itself, not the application.

502: BAD_GATEWAY
Code: EDGE_FUNCTION_INVOCATION_FAILED
ID: fra1::4b98b-1721388668848-b55ea6e26b43

If you are a visitor, please try again later.
If you are the owner, no action is needed.
```

**Comment by nihaopaul** [comment]
same, hitting this also - seems the link on fcamp has expired

**Comment by iRajatDas** [comment]
It's working as of now.

> **Description** Download links in Github and [Firecamp](https://firecamp.io/download) website are linked to this URL https://fcamp.co/mac for Intel/Mac build and it returns error.
> 
> ```
> Error: An internal error occurred with Vercel.
> 
> Your connection is working correctly.
> 
> Vercel is NOT working correctly.
> 
> This is an error with the platform itself, not the application.
> 
> 502: BAD_GATEWAY
> Code: EDGE_FUNCTION_INVOCATION_FAILED
> ID: fra1::4b98b-1721388668848-b55ea6e26b43
> 
> If you are a visitor, please try again later.
> If you are the owner, no action is needed.
> ```

**Comment by siniradam** [comment]
Verified.

**Comment by SylwesterZarebski** [comment]
Please reopen. Domain `fcamp.co` does not exist at all now.
