### ISSUE TITLE
Download Links for Firecamp Desktop Application Redirect to Expired Domain with Random Content

### ISSUE THREAD

**Issue by thetloffline** [firecamp-dev/firecamp#254]
**Description**
Users attempting to download the Firecamp Desktop Application are currently being redirected to a domain that is no longer active. This issue is preventing new installations of the application and is likely affecting overall user experience and adoption.

**Steps to Reproduce**
Try downloading Firecamp desktop app using one of the download links provided on the official Github repo page [LINK](https://github.com/firecamp-dev/firecamp?tab=readme-ov-file#download-firecamp-desktop-application)

**Expected Behavior**
The download links should direct users to the active and correct domain or server where the Firecamp Desktop Application is hosted, allowing them to successfully download and install the application.

**Actual Behavior**
The download links are currently directing users to an inactive domain,  preventing the application from being downloaded.

**Comment by Nishchit14** [comment]
Thank you for informing @thetloffline, The CC was expired. I just renewed it and the domain would be activated in couple of minutes.
