### ISSUE TITLE
[feature]: bulk edit for FormUrlEncode body type

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-dev/firecamp#27]
**Is your feature request related to a problem? Please describe.**
I am not able to bulk edit the form data.

**Describe the solution you'd like**
The form-URL-encode body type table should be bulk-editable. The developer should be able to edit the table in bulk editor with comma-separated values the same as params.

<img width="1058" alt="image" src="https://github.com/firecamp-dev/firecamp/assets/5078921/719dc46a-3a79-40ad-9acf-4472099a169b">

**Comment by thevinitgupta** [comment]
This would be great feature for developer experience, I would love to work on it.

**Comment by Nishchit14** [comment]
@thevinitgupta would be happy to take off with it. Firecmap is Open Source now. If yes then please join the contributors' channel in the [discord server](https://discord.com/invite/8hRaqhK) for more assistance.

**Comment by denishrana09** [comment]
I didn't get the issue, can you describe more in detail, please?

**Comment by Nishchit14** [comment]
@denishrana09 the bulk edit will help to write the `key: value` with a new line instead of the table rows. It's easy in some cases to just edit, copy, and paste the whole table. you can see in the below screenshot, it's the build edit view of headers. 

<img width="719" alt="image" src="https://github.com/firecamp-dev/firecamp/assets/5078921/05604852-479f-4ef4-9b8c-f96d85aa1163">

**Comment by bathini79** [comment]
@Nishchit14  So, this is kind of closed right?

**Comment by Nishchit14** [comment]
No, it's not closed. yet to implement.
