### ISSUE TITLE
[feat] signin and signup button would be there in Tabbar

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-dev/firecamp#35]
If a user is not logged in then there should be easy-to-access SignIn and SignUp buttons would be there at the right side of tab bar. 

<img width="1440" alt="image" src="https://github.com/firecamp-dev/firecamp/assets/5078921/369d389c-d3af-4d1a-a5b7-0395c8c3ffd9">

**Comment by vigneshrams** [comment]
@Nishchit14 Hope this is already fixed. I could see Sign in button on the top right as a guest user. Please check this screenshot.
<img width="1430" alt="image" src="https://github.com/firecamp-dev/firecamp/assets/528924/8b11fef3-557a-48e2-9351-a5a3f9607160">
