### ISSUE TITLE
[bug]: Dark Theme Selection not Persisting in LocalStorage

### ISSUE THREAD

**Issue by ezaz-ahmed** [firecamp-dev/firecamp#45]
**Description:**

**Current Behavior:**
In the "Themes" section of the [application](https://firecamp.dev/), when selecting any dark theme, the `editorTheme` value in `localStorage` is correctly changed from `editor-light` to `editor-dark`. This behavior is functioning as intended and is a positive change. 

**Expected Behavior:**
After selecting a dark theme and changing the `editorTheme` value to `editor-dark` (or `editor-lite`) in `localStorage`, the selection should persist even after reloading the page or navigating back to the application. However, the current behavior is that the `editorTheme` value reverts back to `editor-light` upon reload or returning to the application.

**Steps to Reproduce:**
1. Open the [firecamp.dev](https://firecamp.dev/).
2. Navigate to the "Themes" section.
3. Choose a dark theme (e.g., "Dark Orange").
4. Inspect `localStorage` to verify the change to `editor-dark` (or `editor-lite`).
5. Reload the page or navigate away from the application.
6. Return to the application and observe that the `editorTheme` value in `localStorage` has reverted back to `editor-light`.

**Additional Information:**
- Operating System: Windows 10
- Browser: Google Chrome, version: 116
- Application Version: v3.2.1

This issue prevents users from enjoying their preferred dark theme across sessions, which impacts user experience.

**Comment by bathini79** [comment]
Currently the theme is changing according to the LightPrimary,LightSecondary,DarkPrimary,DarkSecondary . It should be fixed according to thhat right?

**Comment by bathini79** [comment]
https://github.com/firecamp-dev/firecamp/pull/72

**Comment by thevinitgupta** [comment]
Is this issue open?

**Comment by Nishchit14** [comment]
This one is taken. The highest priority for now is #85. If you're interested then I'll help you to jump on it.
