### ISSUE TITLE
Currently the theme is changing according to the LightPrimary,LightSecondary,DarkPrimary,DarkSecondary . It should be fixed according to thhat right?

### ISSUE THREAD

**Issue by bathini79** [firecamp-dev/firecamp#60]
Currently the theme is changing according to the LightPrimary,LightSecondary,DarkPrimary,DarkSecondary , Not Only Dark Mode And Light Mode. It should be fixed according to that right?

**Comment by Nishchit14** [comment]
Thank you for your first. issue @bathini79.

Can you please explain the issue with more clarity? What exactly you're facing the problem with theming options?

**Comment by bathini79** [comment]
Okay The issue is theme is not being stored in the localStorage properly . Its only storing light and dark in localStorage,which is also not working upon every refresh it'll set to default . 
A. Theme should be stored localStorage 
B. It is supposed to LightPrimary,LightSecondary,DarkPrimary,DarkSecondar.

**Comment by Nishchit14** [comment]
duplicate of #45

**Comment by bathini79** [comment]
I believe it is extention of that issue. That issue speaks more about blank and white theme . 
Even if we fix that , there's gonna be other problem the theme will not no which color scheme was applied . Then we have to re write the whole code logic . 
Instead we could tackle the problem together in one go

**Comment by bathini79** [comment]
I'll be doing it

**Comment by bathini79** [comment]
https://github.com/firecamp-dev/firecamp/pull/72
