### ISSUE TITLE
Logo on Doc should redirect back to the website home instead Doc home. 

### ISSUE THREAD

**Issue by shreya-gr** [firecamp-dev/firecamp#75]
**Feedback Description:**
For Firecamp doc - https://firecamp.io/docs , logo on the doc should redirect to the website home instead doc home. 

Feedback by 2 developers. 

**Feedback Type:**
Documentation 

**Suggested Improvement:**

We can implement the supabase style - https://supabase.com
They have use `Supabse docs` and `supabase.com` 2 different links to help users with redirection. 

<img width="1440" alt="Screenshot 2023-09-02 at 12 16 00 PM" src="https://github.com/firecamp-dev/firecamp/assets/21064733/cecb6728-d257-4466-86e0-e5724e9bdb86">

**Comment by d4nnyp73** [comment]
Hi, I would like to give it a shoot! Could you assign this issue to me? 
Cheers! :)

**Comment by msboffl** [comment]
@shreya-gr You want to redirect to this page - https://firecamp.io/

**Comment by Nishchit14** [comment]
@d4nnyp73 @msboffl 

yes, that's true. the logo should redirect to the main website

The doc repo is here
https://github.com/firecamp-dev/firecamp-documentation

**Comment by msboffl** [comment]
Raised PR - Please review (https://github.com/firecamp-dev/firecamp-documentation/pull/5)

**Comment by HarshitDoshi** [comment]
Is this still open, @Nishchit14? I would like to try to work on it.

**Comment by Nishchit14** [comment]
It's taken, I am closing it.
