### ISSUE TITLE
fix zustand warnings

### ISSUE THREAD

**Issue by Nishchit14** [firecamp-dev/firecamp#77]
**Description**
[after migrating to the zustand v4](https://docs.pmnd.rs/zustand/migrations/migrating-to-v4), it shows the warning in console. Follow the migration guide to avoid it.

<img width="1116" alt="image" src="https://github.com/firecamp-dev/firecamp/assets/5078921/6be53e58-73c0-4128-9aa4-1bfa9723f817">

**Comment by onionSequences** [comment]
Hi @Nishchit14 could I take this one?

**Comment by bathini79** [comment]
i'll work on it

**Comment by Nishchit14** [comment]
stage is yours @bathini79

**Comment by Nishchit14** [comment]
hey @bathini79 do you have any update on it?

if you're busy then i'll fix it before we release the new version next week.

**Comment by md-abid-hussain** [comment]
i would like to work on this issue

**Comment by bathini79** [comment]
> hey @bathini79 do you have any update on it?
> 
> if you're busy then i'll fix it before we release the new version next week.

Due to some personal commitments i couldn't be active in the community. But now i'm back and eager to contribute

**Comment by Nishchit14** [comment]
no worries @bathini79, I'll create some more issues in a day. you can pick from there.
