### ISSUE TITLE
[bug]: Playgrounds are getting the @firecamp/types version 0.1.21

### ISSUE THREAD

**Issue by pedrobruneli** [firecamp-dev/firecamp#95]
**Describe the bug**
When trying to `npm run dev` it throws an error saying "Property 'connection' does not exist on type 'IWebSocket'. Did you mean 'connections'?"

**To Reproduce**
1. Clone the project
2. Run pnpm i
3. Run pnpm dev

**Expected behavior**
Should build app and uses the @firecamp/types version 0.2.2

**Screenshots**
![image](https://github.com/firecamp-dev/firecamp/assets/96212888/b15e1186-cf23-4a69-ae8a-22bcc6d87d8d)

**Desktop (please complete the following information):**
 - OS: Windows and Linux
 - Version: 3.2.2

**Additional context**
I tried to run in my local machine (Windows) and a github codespace machine (Ubuntu 20.04.6 LTS)

Maybe there's an inconsistency in pnpm.lock?

**Comment by Nishchit14** [comment]
solved
