### ISSUE TITLE
[bug]: Development server not starting; err_pnpm_recursive_run_first_fail

### ISSUE THREAD

**Issue by ayushsgithub** [firecamp-dev/firecamp#97]
**Describe the bug**
After doing all the steps [From Here](https://github.com/firecamp-dev/firecamp/blob/main/CONTRIBUTING.md), it not starting the development server

**Expected behavior**
Should run the development server at localhost but showing errors in terminal: err_pnpm_recursive_run_first_fail

**Screenshots**
![Screenshot 2023-10-03 152155](https://github.com/firecamp-dev/firecamp/assets/120788538/7e44ffa1-1686-4b4c-94cd-2f865415ad73)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [chrome]
 - Version [117.0.5938.132]

**Additional context**

**Comment by Nishchit14** [comment]
@ayushsgithub can you please try now with the latest main branch? if the issue still exists then please do let me know.

**Comment by Nishchit14** [comment]
need help to reproduce it, feel free to reopen it if you face the same issue again.

**Comment by ayushsgithub** [comment]
> need help to reproduce it, feel free to reopen it if you face the same issue again.

Hey @Nishchit14, thank you for your help, but rn I'm not working on this, btw Thank you so much
